### PR TITLE
Add Chain Tool in frontend

### LINKED ISSUE #177: Allow users to label Scans with chain of Connected Points
## Expected Behavior

Users should be able to label their Scans with chain of connected points. Such points will be then assigned to a given tag.
**Example task:** "Using Connected Points please mark border of the right kidney."

**Tasks to do:**
- [Frontend] New Selection tool that will allow to enter multiple Connected Points,
- [Backend] Extend existing structure and allow to add above Connected Points to the Labels.

**Points should be draggable!** Everyone's not perfect :(
**Connected Points should allow to create a loop (somehow)!**

Proposal for JSON representation in the API (to be discussed):
```json
{
  "points": [{
    "x": 0.5,
    "y": 0.5
  }, {
    "x": 0.5,
    "y": 0.2
  }, {
    "x": 0.1,
    "y": 0.5
  }],
  "slice_index": 0,
  "tag": "SPINE_CENTER",
  "tool": "CONNECTED_POINT",
  "loop": true
}
```

Proposal for UI design (to be discussed):

screen shot 2018-05-24 at 20 36 06

### PR DESCRIPTION
**Pull request by piotrwalkusz1**
Fixes #177 

## Proposed Changes

  - Allow right click on canvas
  - Add Chain Selector
  - Delete hardcoded Selectors styles and add `getStyle()` function
  - Delete `SelectorBase.mouseDrag` field
  - Add common functions to `SelectorBase`
  - Add Actions section
  - Add posibility to redraw to Selectors

screenshot from 2018-07-17 20-57-14

### CODE REVIEW

**Comment by jpowie01** [comment]
> Left click - add new point
> Right click - stop drawing
> To create loop, click on the first point in a chain.

I wonder if this flow will be intuitive for our end users without any training before... I think not :( Maybe we should think about tooltip/dialog/popup help? Or maybe we should add some buttons like "Stop" or "Make loop & Stop"?

How will users know what to do? :) This can be solved in another patch or even we should consider a UX design for this :)

For me - code looks good but someone else (@Darkoon?) should check it out.

**Comment by piotrwalkusz1** [comment]
What do you think about this solution: after making the first point of a chain, Actions label appears?
screenshot from 2018-07-14 23-37-43

**Comment by Darkoon** [comment]
@piotrwalkusz1 Looks nice, I think it will be good for now. Don't bother with styles, it will be added later :)

**Comment by jpowie01** [comment]
**(Future Proposal)** Maybe these action buttons could be a Material Design's Chips (with optional icons)?
https://material.angular.io/components/chips/overview

screen shot 2018-07-15 at 17 35 11

**Comment by piotrwalkusz1** [comment]
Unfortunately, Material Design's Chips have a few terrible features, e.g. Click works even if an element is disabled and Chip has to be selected to have color (this can be problematic https://stackoverflow.com/questions/47021161/incorrect-behaviour-when-selecting-chips-in-angular-material). I used normal buttons, but I styled them to looks like in your example.

**Comment by jpowie01** [comment]
Looks fine for me! :)

Yeah... Angular Material seems to be cool only if you copy and paste something from their docs... Once you go deeper, it very often behaves strange and weird...

**Pull request merged**
